TEST_CASES = [
  [99, 'ninety-nine'],
  [95, 'ninety-five'],
  [90, 'ninety'],
  [89, 'eighty-nine'],
  [85, 'eighty-five'],
  [80, 'eighty'],
  [79, 'seventy-nine'],
  [75, 'seventy-five'],
  [70, 'seventy'],
  [69, 'sixty-nine'],
  [65, 'sixty-five'],
  [60, 'sixty'],
  [59, 'fifty-nine'],
  [55, 'fifty-five'],
  [50, 'fifty'],
  [49, 'forty-nine'],
  [45, 'forty-five'],
  [40, 'forty'],
  [39, 'thirty-nine'],
  [35, 'thirty-five'],
  [30, 'thirty'],
  [29, 'twenty-nine'],
  [25, 'twenty-five'],
  [20, 'twenty'],
  [19, 'nineteen'],
  [18, 'eighteen'],
  [17, 'seventeen'],
  [16, 'sixteen'],
  [15, 'fifteen'],
  [14, 'fourteen'],
  [13, 'thirteen'],
  [12, 'twelve'],
  [11, 'eleven'],
  [10, 'ten'],
  [9, 'nine'],
  [8, 'eight'],
  [7, 'seven'],
  [6, 'six'],
  [5, 'five'],
  [4, 'four'],
  [3, 'three'],
  [2, 'two'],
  [1, 'one']
]

SPECIAL_TEST_CASES = [
  [0, 'zero'],
  [-0, 'zero'],
  [1000, nil],
  [-1000, nil],
  [100, nil],
  [-100, nil],
  [nil, nil],
  ['a', nil]
]
